// utils/localUpload.js
const fs = require('fs').promises;
const path = require('path');

class LocalUpload {
  constructor(baseUrl) {
    this.baseUrl = baseUrl || process.env.CALLBACK_BASE_URL || 'http://localhost:3000';
  }

  /**
   * Save image to local storage
   * @param {string} sourcePath - Path to source file
   * @param {string} folder - Folder name (e.g., 'ai-influencer', 'photo-product')
   * @param {number} id - Record ID for filename
   * @returns {Promise<{localPath: string, publicUrl: string}>}
   */
  async saveImage(sourcePath, folder, id) {
    try {
      const ext = path.extname(sourcePath);
      const filename = `image_${id}_${Date.now()}${ext}`;
      const uploadDir = path.join('uploads', folder, 'images');
      const localPath = path.join(uploadDir, filename);

      await fs.mkdir(uploadDir, { recursive: true });
      await fs.copyFile(sourcePath, localPath);

      const publicUrl = `${this.baseUrl}/uploads/${folder}/images/${filename}`;

      return { localPath, publicUrl };
    } catch (error) {
      console.error('Save image error:', error);
      throw error;
    }
  }

  /**
   * Save result image (generated by API)
   * @param {string} sourcePath - Path to source file
   * @param {string} folder - Folder name
   * @param {number} id - Record ID
   * @returns {Promise<{localPath: string, publicUrl: string}>}
   */
  async saveResult(sourcePath, folder, id) {
    try {
      const ext = path.extname(sourcePath);
      const filename = `result_${id}_${Date.now()}${ext}`;
      const uploadDir = path.join('uploads', folder, 'results');
      const localPath = path.join(uploadDir, filename);

      await fs.mkdir(uploadDir, { recursive: true });
      await fs.copyFile(sourcePath, localPath);

      const publicUrl = `${this.baseUrl}/uploads/${folder}/results/${filename}`;

      return { localPath, publicUrl };
    } catch (error) {
      console.error('Save result error:', error);
      throw error;
    }
  }

  /**
   * Download file from URL and save locally
   * @param {string} url - URL to download
   * @param {string} folder - Folder name
   * @param {number} id - Record ID
   * @param {string} prefix - Filename prefix (default: 'download')
   * @returns {Promise<{localPath: string, publicUrl: string}>}
   */
  async downloadAndSave(url, folder, id, prefix = 'download') {
    try {
      const axios = require('axios');
      const response = await axios.get(url, { responseType: 'arraybuffer' });
      
      // Detect extension from content-type or URL
      let ext = '.jpg';
      const contentType = response.headers['content-type'];
      if (contentType) {
        if (contentType.includes('png')) ext = '.png';
        else if (contentType.includes('webp')) ext = '.webp';
        else if (contentType.includes('jpeg') || contentType.includes('jpg')) ext = '.jpg';
      } else {
        const urlExt = path.extname(url.split('?')[0]);
        if (urlExt) ext = urlExt;
      }

      const filename = `${prefix}_${id}_${Date.now()}${ext}`;
      const uploadDir = path.join('uploads', folder, 'downloads');
      const localPath = path.join(uploadDir, filename);

      await fs.mkdir(uploadDir, { recursive: true });
      await fs.writeFile(localPath, response.data);

      const publicUrl = `${this.baseUrl}/uploads/${folder}/downloads/${filename}`;

      return { localPath, publicUrl };
    } catch (error) {
      console.error('Download and save error:', error);
      throw error;
    }
  }
}

module.exports = LocalUpload;